[build]
  command = "pnpm run build:functions"
  functions = "netlify/functions-dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[functions]
  node_bundler = "none"
  directory = "netlify/functions-dist"
  included_files = [
    "netlify/functions-dist/**",
    "src/**"
  ]
